setwd("C:/Users/Divya Sharma/Desktop/myprojects/sentiment")
install.packages('twitteR', dependencies=T)
library(twitteR)
install.packages('plyr')
library(plyr)
install.packages("httpuv")
library(httpuv)
setup_twitter_oauth("API KEY","API SECRET KEY")
tweets= searchTwitter("#abortion",n=1500)
length(tweets)
tweets.text=laply(tweets,function(t)t$getText())
pos=scan('positive-words.txt',what='character',comment.char = ';')
neg=scan('negative-words.txt',what='character',comment.char = ';')
source('sentiment.r')
analysis= score.sentiment(tweets.text,pos.words,neg.words)
table(analysis$score)
mean(analysis$score)
median(analysis$score)
hist(analysis$score)
